### ISSUE TITLE
JVM is not embedded

### ISSUE THREAD

**Issue by jhagege** [libgdx/packr#112]
Hi, when running the packr.jar with config.json, I get an output directory with:
- native executable (linux x64)
- JRE
- jar file

But the JRE doesn't get embedded in the executable file.
i.e: If I move the file from the output folder, it won't be able to run, because it won't find the JRE.

Is there a way to embed the JRE in the native executable file ?

Thanks !

**Comment by sszigeti** [comment]
If you're absolutely sure you want a single installer .exe, you'll need a separate application like Inno Setup which performs this next step for you (after you've created everything with Packr).

Please note that you'll probably need to digitally sign your installer, otherwise the users will be prompted that they're about to install an unsigned application. As far as I know signing an installer requires a paid certificate, and I'm not aware of any sufficient, free service which could supply you with one. (Not even Let'sEncrypt would help.)

However, in case you're preparing to release an application via Steam, you'll be absolutely fine with the results Packr provides. (During review they'll notify you that a virustotal.com check has flagged your executable, but despite being an annoyance, it's not a showstopper, so they will let you proceed. At this point I haven't found a way for fixing this, as it's not even a Packr specific issue. More details on this: https://github.com/libgdx/packr/issues/113)

**Comment by dtromb** [comment]
You could pretty easily modify packr.cpp to do whatever you need to to do to find the system JRE if you don't want to distribute one.   If you choose to distribute, it's 100% necessary to /install/, since it's impossible to dlopen() a file from within a JAR - it's got to be on a filesystem.   So, if it's a one-exe-only distribution, the first thing it's going to do is write out the /jre directory anyhow.  So why not just distribute it?

**Comment by karlsabo** [comment]
This is beyond the scope of packr. [GraalVM](https://www.graalvm.org/) might be more of what you're after if you want a single executable file, or [jpackage](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html) if you're wanting an installer.
