### ISSUE TITLE
Virustotal.com flags exe generated with Packr

### ISSUE THREAD

**Issue by sszigeti** [libgdx/packr#113]
I've just received a notification from Steam that a virustotal.com check has flagged my game that I've submitted to them, a game built in LibGDX and packaged with packr.

https://www.virustotal.com/#/file/f94c063ff3098b1905996ff9ff03c1c2cc099a8a37e1200007aa90d1c28c276c/detection

The "details" tab lists file names where the same pattern have been found, and I recognise two of those as also being LibGDX games (FlatFatCat and Timbertales).

I uploaded only the exe (that packr has built for me) to virustotal.com, and the result was the same, and virustotal.com thinks the file name is "mirador.exe" -- but this name isn't familiar to me.

Can you help me figure out what's going on here?

**Comment by code-disaster** [comment]
That "CAT-QuickHeal" one is new. Must be AV feature of the month, September edition.

The different names is just different Java games using the same version of the packr executable, so the file hash is identical.

My short, personal & of course biased answer is: AV "heuristics" suck.

Longer answer: You'll very likely see a different result next month, with other scanners reporting something about "generic", "suspicious", "unsafe" or "heuristics". AV report details are difficult to find, often enough the vendor "info" pages aren't much more than glorified marketing sheets, so its pretty unclear *what* they actually complain about, and how to avoid it.

Maybe, maaaaybe it's even just they see the same executable in different products. Who the hell knows?

With the non-Steam version of our game we inject a custom icon using ResHacker. This changes the file hash, which leads to different Virustotal reports. Sometimes its clean, sometimes its just a *different* set of AV scanners complaining.

I also had some disputable success with adding a self-signed certificate to the executable. This made all scanners shut up except one, which then complained about the untrustworthy certificate instead. So this may be worth a try for you too, though it's a chore to setup. Here are some links I found helpful:

https://blog.didierstevens.com/2008/12/30/howto-make-your-own-cert-with-openssl/
https://blog.didierstevens.com/2008/12/31/howto-add-a-digital-signature-to-executables/

If you try that, I'd be happy to learn about your results. Thing is, it probably doesn't change much if we just self-sign the prebuilt executables here, because then it might be look just as suspicious as before to AV scanners. Maybe even more so, since then its ... well, self-signed. Nobody here will pay a shitload of money to get some *officially* signed cert.

/rant off

**Comment by sszigeti** [comment]
Thank you for explaining this weird situation in detail and offering workarounds! I must say seeing that you've helped me twice already in just a couple of days (I had a question regarding Steamworks4j at the LibGDX forum) fills me with admiration and gratitude. :)

I couldn't inject an icon with ResHacker because in the exe there wasn't an "Icon Group" I could update nor could I create one, but using a trial version of Resource Tuner I've made it happen. Unfortunately this time not 3 but 12 AV applications were waving red flags at virustotal.com.

Now I also know that **this issue isn't only affecting Packr**, because a Launch4j build has also raised a red flag, albeit from an application called "Jiangmin", but still, it wasn't a clean solution either.

I also feel that using a self-signed certificate wouldn't help because of the reasons you've mentioned.

I've contacted other LibGDX game developers on Steam and they also had similar experiences, yet they went ahead and published their games with success. I think at this point I'm also going to accept the circumstances and proceed with my release.
