### ISSUE TITLE
Add XZ (LZMA) support

### ISSUE THREAD

**Issue by donmor** [libgdx/packr#183]
I want to distribute my jar with a cdrom, expected to running on win32, win64, linux, mac and raspbian. I then found that with all necessary jvms on the disc, there's no space for data (over 600MB!), so I have to pack all jvms to a .txz file and unpack it with tar. I then found this project, which can deploy jvms in .tar.gz, but no .txz. I hope there's an update for the xz support in the future.

**Comment by karlsabo** [comment]
I don't think packr does what you're hoping it does. It generates a configuration file and then has a native executable to make your Java app look like a native app. It takes a JRE as a parameter when created its output <https://github.com/libgdx/packr#output> so that there's a predetermined file structure for loading the JVM shared library object. That JRE can be a tar.xz or txz, but that's the least of your problems.

1. The native launcher (Packr launcher) does not extract JREs, it loads the jvm[.dll] from a JRE directory to launch an application.
2. There is no AArch support.
3. There is no x86 support (win32).

**Comment by karlsabo** [comment]
You should look into [jpackage](https://docs.oracle.com/en/java/javase/14/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A), maybe the installers it generates could fit onto a CD for all your targets.
