### ISSUE TITLE
Apple API token id?

### ISSUE THREAD

**Issue by seinecle** [libgdx/packr#189]
Thank you for a very useful description of the process for Apple notarization, in the readme. At some point you mention the "API token for your Apple developer account", to be used to check the status of the notarization. I can't find where to create this token from my Apple dev account. The closest I find is to create an API secret from my App Store. Is this it? In which case, does it mean I should create a record for my app in the App Store? (I didn't plan to, but I could).

**Comment by karlsabo** [comment]
Sorry, I didn't use the proper Apple name when writing that read me. Apple cake it app specific password: https://support.apple.com/en-us/HT204397

**Comment by karlsabo** [comment]
"Add the username and password options to supply your App Store Connect credentials. Because App Store Connect now requires two-factor authentication (2FA) on all accounts, you must create an app-specific password for altool, as described in Using app-specific passwords."

https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow

**Comment by seinecle** [comment]
Thank you!

**Comment by seinecle** [comment]
9
