### ISSUE TITLE
Artifactory down?

### ISSUE THREAD

**Issue by Frotty** [libgdx/packr#199]
Getting this error:
```
   > Could not resolve com.badlogicgames.packr:packr:3.0.3.
     Required by:
         project :deploy
      > Could not resolve com.badlogicgames.packr:packr:3.0.3.
         > Could not get resource 'https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr/3.0.3/packr-3.0.3.pom'.
            > Could not HEAD 'https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr/3.0.3/packr-3.0.3.pom'.
               > Connect to artifactory.nimblygames.com:443 [artifactory.nimblygames.com/73.26.206.4, artifactory.nimblygames.com/2601:8c0:37f:60cb:ccc3:aab3:3bfc:e620] failed: connect timed out
```

**Comment by karlsabo** [comment]
Yes, Comcast internet outage.

**Comment by karlsabo** [comment]
It's back. Please update your URL to <https://artifactory.nimblygames.com/artifactory/ng-public> so you can download both snapshots and releases, the -snapshot and -release versions are for publishing. Artifactory will give you an error if you try to get a snapshot from the -release version and vice versa. I mistakenly listed those instead of the combined "virtual" repository that should be used for downloading. I fixed the readme to point folks to the correct URL.
