### ISSUE TITLE
The file permissions aren't preserved when unzipping and copying the JRE

### ISSUE THREAD

**Issue by ghost** [libgdx/packr#23]
I tried to use Packr both with a JRE on my local file system and by passing a URL. Just before the decompression, in both cases, all files in jre/bin are executable. Just after the decompression, in {out}/Contents/MacOS/tmp, you can see that those files are no longer executable as ZipUtil.unpack() does nothing to preserve file permissions:
https://github.com/zeroturnaround/zt-zip/blob/master/src/main/java/org/zeroturnaround/zip/ZipUtil.java#L915

**Comment by 3xp0n3nt** [comment]
Actually, it causes `ProcessBuilder` to throw:

```
java.io.IOException: Cannot run program "java": error=0, spawn failed
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

@code-disaster Can we please re-open this issue?

It shouldn't matter, but just in case:

OS: OS X 10.12.1 (Sierra)
JRE: 1.8.0_72-b15 (Oracle)

P.S. Maybe related to #70?

**Comment by 3xp0n3nt** [comment]
Just in case there was any doubt, the issue is resolved by `chmod +x jre/bin/java`.

**Comment by 3xp0n3nt** [comment]
@code-disaster This could be remedied in `Packr.java` at [L208](https://github.com/libgdx/packr/blob/master/src/main/java/com/badlogicgames/packr/Packr.java#L208), [L220](https://github.com/libgdx/packr/blob/master/src/main/java/com/badlogicgames/packr/Packr.java#L220), & [L230](https://github.com/libgdx/packr/blob/master/src/main/java/com/badlogicgames/packr/Packr.java#L230) by using Java 7 nio: [`Files.copy (source, target, StandardCopyOption.COPY_ATTRIBUTES)`](https://docs.oracle.com/javase/tutorial/essential/io/copy.html) in conjunction with nio [Path Operations](https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html) instead of Apache Commons IO.

**Comment by 3xp0n3nt** [comment]
Ah. Looks like you're still trying to [support Java 6](https://github.com/libgdx/packr/blob/master/pom.xml#L74). Can we require Java 7 and get access to nio?

**Comment by code-disaster** [comment]
- Java 6: historical reasons. Just didn't bother yet.
- Attributes: good point, but I don't know if this works when e.g. packing a Mac or Linux bundle on a Windows host, because of the different file system attributes.
- ProcessBuilder: just curious, why do you want to fork `java`?

**Comment by 3xp0n3nt** [comment]
> ProcessBuilder: just curious, why do you want to fork java?

To launch a host-and-play java game server from a java client.

> Attributes: good point, but I don't know if this works when e.g. packing a Mac or Linux bundle on a Windows host, because of the different file system attributes.

Only one way to find out! But think about it - packr is already failing to preserve *any* permissions. Why not make a best attempt with nio, and at least log a warning if permissions won't be preserved. That would be 100x better than the current behavior.
