### ISSUE TITLE
Exe created by packr flagged as virus

### ISSUE THREAD

**Issue by kading** [libgdx/packr#63]
We use packr to generate an .exe for our game. However, this Windows exe gets flagged as malware by a fairly wide range of virus scanners. 

Here is the complete report:
https://www.virustotal.com/en/file/528b2fe72c5e478ed5212b2f0b04e98275a7d626fb046076407f8b90be0d857c/analysis/1466068465/

Did anyone else experience this issue? Am I right to suspect it has nothing to do with our actual application (as the exe does not contain any of our actual code)? Not sure how to prevent this.

**Comment by code-disaster** [comment]
What version of packr do you use? Where did you download the executable from, did you compile it yourself, and/or did you modify it afterwards?

The reason I'm asking is because the file size does not match. Here's the report of the Win32 executable uploaded from the Git repository:
https://www.virustotal.com/en/file/1fe89804847a6c057180b39f83ca3da1099bf458a7d1ab1c83120204a218779a/analysis/1466070450/

By the report it looks like you've injected an icon resource. Checksums of the other sections are the same, so I have no idea how scanners assume its malicious.

If you've added the icon yourself, maybe you can try to alter that resource, and see if this pleases the AV gods. If you didn't ... well then you should check your source of the packr version.

**Comment by kading** [comment]
Thank you for the incredibly fast reply. You are completely right. As part of our build script we also use [rcedit](https://github.com/atom/rcedit) to set an icon on the file. For some reason this caused the file to become flagged as malware by some AV programs.

I've simply removed the rcedit build step for now and will look for an alternative. Sorry for the false alarm and thanks for the help! Great program you've created here :).

**Comment by code-disaster** [comment]
I would not be surprised if you just need to alter a few pixels of your icon image. AV heuristics are a plague.
