### ISSUE TITLE
Removing of the JRE

### ISSUE THREAD

**Issue by zimmerrol** [libgdx/packr#84]
Hello,
is it somehow possible to do not include the JRE for a macOS build? Beacause most of the time the user has already installed a java runtime, so there is no need to ship an extra version with the app-bundle - or am I missing something?
Regards.

**Comment by code-disaster** [comment]
> am I missing something?

Based on experience with our game on Steam, "most of the time" won't cut it. I wouldn't go that route, esp. if its a game you are shipping.

But may I ask: why do you want to use packr then? Bundling with a JRE is *the* primary objective of this project. Everything else it does is just a matter of automation and convenience.

**Comment by danstolz** [comment]
I was considering using this because where our application is to be installed, there is not a file association for .jar files. So our executable jar installer (created by IzPack) can't be launched by double-clicking. We are trying to create an .exe file that will unpack (compression not needed) the installer jar and launch it by simulating a command-line call of 'java -jar <installer.jar>'

**Comment by aggsol** [comment]
As long as you re-package your game with every JRE (security)update that might be a way to go.

**Comment by karlsabo** [comment]
macOS no longer includes a JRE, so I'm going to close this issue. I've found it's best to ship a bundled JRE on all platforms.
